version: "3"
services:
  db:
    image: "postgres:latest"
    env_file: ".env"
    ports:
      - "5432"

  broker:
    build:
      context: ./
    image: hive-broker
    environment:
      POSTGRES_PORT : 5432
      POSTGRES_HOST : db
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : hive
      POSTGRES_DB : hive
    ports:
      - "8080"
